package com.aperto.magnolia.edittools.m6.action;

import com.aperto.magnolia.edittools.util.LinkService;
import com.vaadin.server.Page;
import info.magnolia.jcr.util.NodeUtil;
import info.magnolia.ui.ValueContext;
import info.magnolia.ui.api.action.AbstractAction;
import info.magnolia.ui.api.action.ConfiguredActionDefinition;

import javax.inject.Inject;
import javax.jcr.Node;

/**
 * Opens a new tab with location generated by {@link LinkService#getPublicLink(String)}.
 *
 * @author Philipp Güttler (Aperto GmbH)
 * @since 19.02.2021
 */
public class OpenPagePublishedLocationAction extends AbstractAction<ConfiguredActionDefinition> {

    private final ValueContext<Node> _valueContext;
    private final LinkService _linkService;

    @Inject
    public OpenPagePublishedLocationAction(final OpenPagePublishedLocationActionDefinition definition, final ValueContext<Node> valueContext, final LinkService linkService) {
        super(definition);
        _valueContext = valueContext;
        _linkService = linkService;
    }

    @Override
    public void execute() {
        _valueContext.getSingle()
            .map(NodeUtil::getPathIfPossible)
            .map(_linkService::getPublicLink)
            .ifPresent(url -> Page.getCurrent().open(url, "_blank"));
    }
}
